// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_km2264.Models;

namespace Mission06_km2264.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230222013207_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_km2264.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sci-Fi"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Western"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Documentary"
                        });
                });

            modelBuilder.Entity("Mission06_km2264.Models.EnterMovieResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 12,
                            Director = "Nobuhiro Doi",
                            Edited = false,
                            Lent = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Flying Colors",
                            Year = (short)2015
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Director = "Nobuhiro Doi",
                            Edited = false,
                            Lent = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "We Made a Beautiful Bouquet",
                            Year = (short)2021
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Director = "Testuro Kodama",
                            Edited = false,
                            Lent = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Dragonball Super: Super Hero",
                            Year = (short)2022
                        });
                });

            modelBuilder.Entity("Mission06_km2264.Models.EnterMovieResponse", b =>
                {
                    b.HasOne("Mission06_km2264.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
